### ISSUE TITLE
Request: multiple urls from text file

### ISSUE THREAD

**Issue by bascurtiz** [subdigital/kv-downloader#4]
Handy tool! Why they don't have such function on the site itself, beats me.

Could u make it so, that it accepts a text-file with urls per line to download multiple ones after another?

It takes around 4 mins to download one now, but I have around 50 multitracks tops. I'd like to just download them overnight in one-go.

**Comment by subdigital** [comment]
Thank you! Though I am not sure I want to offer this for a few reasons:
* I caution people not to abuse this tool, I wouldn't want anyone's account to be banned. I don't have any control over that and it could mean losing access to a lot of purchased content.
* Since this is driving a browser with automation, it is inherently flaky. Sometimes it doesn't work and I have to retry it. If you did 50 in a row, how would you know which finished successfully?
* And finally, technically this is doable in a bash script, since the entire flow is blocking. Something along the lines of:

```bash
while IFS= read -r SONG; do
  kv-downloader download $SONG
  sleep 30
done < songs.txt
```
